import { Branch, Shift, Subject, Teacher, Room, SchoolClass } from "@/types";

export const initialBranches: Branch[] = [
  { id: "b1", schoolId: "school_1", name: "Asosiy Bino (Bosh korpus)", address: "Toshkent sh., Chilonzor 9", isMain: true },
  { id: "b2", schoolId: "school_1", name: "1-Filial (Boshlang'ich binosi)", address: "Toshkent sh., Chilonzor 10", isMain: false },
];

export const initialShifts: Shift[] = [
  { id: "s1", schoolId: "school_1", name: "1-Smena (Ertalabki)", startTime: "08:00", endTime: "13:00", periodsCount: 6 },
  { id: "s2", schoolId: "school_1", name: "2-Smena (Tushdan keyingi)", startTime: "13:15", endTime: "18:00", periodsCount: 6 },
];

export const initialRooms: Room[] = [
  { id: "r1", schoolId: "school_1", branchId: "b1", name: "Asosiy Sport Zal", roomType: "GYM", capacity: 40 },
  { id: "r2", schoolId: "school_1", branchId: "b1", name: "1-Kompyuter Lab", roomType: "COMP_LAB", capacity: 30 },
  { id: "r3", schoolId: "school_1", branchId: "b1", name: "Fizika & Kimyo Lab", roomType: "LAB", capacity: 35 },
  { id: "r4", schoolId: "school_1", branchId: "b1", name: "Ochiq Futbol Maydoni", roomType: "OUTDOOR_PITCH", capacity: 60 },
  { id: "r5", schoolId: "school_1", branchId: "b2", name: "Kichik Sport Zali (Boshlang'ich)", roomType: "GYM", capacity: 30 },
];

export const initialSubjects: Subject[] = [
  { id: "sub_mat", schoolId: "school_1", name: "Matematika / Algebra", shortName: "Mat", colorTag: "#3B82F6", difficultyScore: 11, allowDoubleLesson: true },
  { id: "sub_ona", schoolId: "school_1", name: "Ona tili va adabiyot", shortName: "Ona tili", colorTag: "#EC4899", difficultyScore: 9, allowDoubleLesson: false },
  { id: "sub_ing", schoolId: "school_1", name: "Ingliz tili (Chet tili)", shortName: "Ingliz", colorTag: "#8B5CF6", difficultyScore: 8, allowDoubleLesson: false },
  { id: "sub_fiz", schoolId: "school_1", name: "Fizika", shortName: "Fizika", colorTag: "#06B6D4", difficultyScore: 10, allowDoubleLesson: true, requiresRoomType: "LAB" },
  { id: "sub_kim", schoolId: "school_1", name: "Kimyo", shortName: "Kimyo", colorTag: "#10B981", difficultyScore: 10, allowDoubleLesson: true, requiresRoomType: "LAB" },
  { id: "sub_bio", schoolId: "school_1", name: "Biologiya", shortName: "Bio", colorTag: "#84CC16", difficultyScore: 7, allowDoubleLesson: false },
  { id: "sub_tar", schoolId: "school_1", name: "Tarix", shortName: "Tarix", colorTag: "#F59E0B", difficultyScore: 7, allowDoubleLesson: false },
  { id: "sub_geo", schoolId: "school_1", name: "Geografiya", shortName: "Geo", colorTag: "#14B8A6", difficultyScore: 6, allowDoubleLesson: false },
  { id: "sub_inf", schoolId: "school_1", name: "Informatika va AT", shortName: "Info", colorTag: "#6366F1", difficultyScore: 8, allowDoubleLesson: false, requiresRoomType: "COMP_LAB" },
  { id: "sub_jism", schoolId: "school_1", name: "Jismoniy tarbiya", shortName: "Jismoniy", colorTag: "#EF4444", difficultyScore: 2, allowDoubleLesson: false, requiresRoomType: "GYM" },
  { id: "sub_tasv", schoolId: "school_1", name: "Tasviriy san'at / Musiqa", shortName: "San'at", colorTag: "#D946EF", difficultyScore: 1, allowDoubleLesson: false },
  { id: "sub_tarb", schoolId: "school_1", name: "Tarbiya", shortName: "Tarbiya", colorTag: "#F97316", difficultyScore: 3, allowDoubleLesson: false },
];

export const initialTeachers: Teacher[] = [
  {
    id: "t_alimov",
    schoolId: "school_1",
    fullName: "Alimov Jamshid Qodirovich",
    phone: "+998 90 123 45 67",
    weeklyHourCapacity: 24,
    maxConsecutiveHours: 4,
    subjectIds: ["sub_mat"],
    branchIds: ["b1"],
    availabilities: [
      { teacherId: "t_alimov", dayOfWeek: 4, period: 1, isAvailable: false }, // Payshanba metod kuni
      { teacherId: "t_alimov", dayOfWeek: 4, period: 2, isAvailable: false },
      { teacherId: "t_alimov", dayOfWeek: 4, period: 3, isAvailable: false },
      { teacherId: "t_alimov", dayOfWeek: 4, period: 4, isAvailable: false },
      { teacherId: "t_alimov", dayOfWeek: 4, period: 5, isAvailable: false },
      { teacherId: "t_alimov", dayOfWeek: 4, period: 6, isAvailable: false },
    ],
  },
  {
    id: "t_karimova",
    schoolId: "school_1",
    fullName: "Karimova Nigora Shavkatovna",
    phone: "+998 93 987 65 43",
    weeklyHourCapacity: 22,
    maxConsecutiveHours: 4,
    subjectIds: ["sub_ona"],
    branchIds: ["b1"],
  },
  {
    id: "t_johnson",
    schoolId: "school_1",
    fullName: "Azizov Sardor Dilshodovich (Ingliz)",
    phone: "+998 94 333 22 11",
    weeklyHourCapacity: 20,
    maxConsecutiveHours: 4,
    subjectIds: ["sub_ing"],
    branchIds: ["b1", "b2"],
  },
  {
    id: "t_tursunov",
    schoolId: "school_1",
    fullName: "Tursunov Bobur Ergash o'g'li (Fizika)",
    phone: "+998 91 555 44 33",
    weeklyHourCapacity: 18,
    maxConsecutiveHours: 4,
    subjectIds: ["sub_fiz"],
    branchIds: ["b1"],
  },
  {
    id: "t_rasulova",
    schoolId: "school_1",
    fullName: "Rasulova Malika Anvarovna (Kimyo/Bio)",
    phone: "+998 97 777 88 99",
    weeklyHourCapacity: 20,
    maxConsecutiveHours: 4,
    subjectIds: ["sub_kim", "sub_bio"],
    branchIds: ["b1"],
  },
  {
    id: "t_saidov",
    schoolId: "school_1",
    fullName: "Saidov Farrux Sherzodovich (Tarix)",
    phone: "+998 99 111 22 33",
    weeklyHourCapacity: 18,
    maxConsecutiveHours: 4,
    subjectIds: ["sub_tar"],
    branchIds: ["b1"],
  },
  {
    id: "t_xolmatov",
    schoolId: "school_1",
    fullName: "Xolmatov Ilhom Baxtiyorovich (Informatika)",
    phone: "+998 90 222 33 44",
    weeklyHourCapacity: 18,
    maxConsecutiveHours: 4,
    subjectIds: ["sub_inf"],
    branchIds: ["b1"],
  },
  {
    id: "t_jismoniy",
    schoolId: "school_1",
    fullName: "Qurbonov Jasur Rustamovich (Jismoniy)",
    phone: "+998 93 444 55 66",
    weeklyHourCapacity: 24,
    maxConsecutiveHours: 5,
    subjectIds: ["sub_jism"],
    branchIds: ["b1", "b2"],
  },
  {
    id: "t_boshlangich1",
    schoolId: "school_1",
    fullName: "Mirzayeva Gulnoza O'ktamovna",
    phone: "+998 90 777 11 22",
    weeklyHourCapacity: 20,
    maxConsecutiveHours: 4,
    subjectIds: ["sub_mat", "sub_ona", "sub_tarb"],
    branchIds: ["b2"],
  },
];

export const initialClasses: SchoolClass[] = [
  {
    id: "c_5a",
    schoolId: "school_1",
    branchId: "b1",
    shiftId: "s1",
    name: "5-A",
    grade: 5,
    isPrimary: false,
    subjects: [
      { classId: "c_5a", subjectId: "sub_mat", teacherId: "t_alimov", weeklyHours: 5 },
      { classId: "c_5a", subjectId: "sub_ona", teacherId: "t_karimova", weeklyHours: 4 },
      { classId: "c_5a", subjectId: "sub_ing", teacherId: "t_johnson", weeklyHours: 3 },
      { classId: "c_5a", subjectId: "sub_tar", teacherId: "t_saidov", weeklyHours: 2 },
      { classId: "c_5a", subjectId: "sub_inf", teacherId: "t_xolmatov", weeklyHours: 1 },
      { classId: "c_5a", subjectId: "sub_jism", teacherId: "t_jismoniy", weeklyHours: 2 },
    ],
  },
  {
    id: "c_5b",
    schoolId: "school_1",
    branchId: "b1",
    shiftId: "s1",
    name: "5-B",
    grade: 5,
    isPrimary: false,
    subjects: [
      { classId: "c_5b", subjectId: "sub_mat", teacherId: "t_alimov", weeklyHours: 5 },
      { classId: "c_5b", subjectId: "sub_ona", teacherId: "t_karimova", weeklyHours: 4 },
      { classId: "c_5b", subjectId: "sub_ing", teacherId: "t_johnson", weeklyHours: 3 },
      { classId: "c_5b", subjectId: "sub_tar", teacherId: "t_saidov", weeklyHours: 2 },
      { classId: "c_5b", subjectId: "sub_inf", teacherId: "t_xolmatov", weeklyHours: 1 },
      { classId: "c_5b", subjectId: "sub_jism", teacherId: "t_jismoniy", weeklyHours: 2 },
    ],
  },
  {
    id: "c_8a",
    schoolId: "school_1",
    branchId: "b1",
    shiftId: "s1",
    name: "8-A",
    grade: 8,
    isPrimary: false,
    subjects: [
      { classId: "c_8a", subjectId: "sub_mat", teacherId: "t_alimov", weeklyHours: 5 },
      { classId: "c_8a", subjectId: "sub_fiz", teacherId: "t_tursunov", weeklyHours: 3 },
      { classId: "c_8a", subjectId: "sub_kim", teacherId: "t_rasulova", weeklyHours: 2 },
      { classId: "c_8a", subjectId: "sub_bio", teacherId: "t_rasulova", weeklyHours: 2 },
      { classId: "c_8a", subjectId: "sub_ona", teacherId: "t_karimova", weeklyHours: 3 },
      { classId: "c_8a", subjectId: "sub_ing", teacherId: "t_johnson", weeklyHours: 2 },
      { classId: "c_8a", subjectId: "sub_jism", teacherId: "t_jismoniy", weeklyHours: 2 },
    ],
  },
  {
    id: "c_9a",
    schoolId: "school_1",
    branchId: "b1",
    shiftId: "s1",
    name: "9-A",
    grade: 9,
    isPrimary: false,
    subjects: [
      { classId: "c_9a", subjectId: "sub_mat", teacherId: "t_alimov", weeklyHours: 5 },
      { classId: "c_9a", subjectId: "sub_fiz", teacherId: "t_tursunov", weeklyHours: 3 },
      { classId: "c_9a", subjectId: "sub_kim", teacherId: "t_rasulova", weeklyHours: 2 },
      { classId: "c_9a", subjectId: "sub_tar", teacherId: "t_saidov", weeklyHours: 2 },
      { classId: "c_9a", subjectId: "sub_inf", teacherId: "t_xolmatov", weeklyHours: 2 },
      { classId: "c_9a", subjectId: "sub_jism", teacherId: "t_jismoniy", weeklyHours: 2 },
    ],
  },
  {
    id: "c_1a",
    schoolId: "school_1",
    branchId: "b2",
    shiftId: "s1",
    name: "1-A",
    grade: 1,
    isPrimary: true,
    subjects: [
      { classId: "c_1a", subjectId: "sub_mat", teacherId: "t_boshlangich1", weeklyHours: 4 },
      { classId: "c_1a", subjectId: "sub_ona", teacherId: "t_boshlangich1", weeklyHours: 4 },
      { classId: "c_1a", subjectId: "sub_tarb", teacherId: "t_boshlangich1", weeklyHours: 1 },
      { classId: "c_1a", subjectId: "sub_jism", teacherId: "t_jismoniy", weeklyHours: 2 },
      { classId: "c_1a", subjectId: "sub_ing", teacherId: "t_johnson", weeklyHours: 2 },
    ],
  },
];
